# Configuration du Solveur Physique
solver:
  time_step_physique: 1.0e-6   # [defaut=1.0e-6] Le pas de temps d'intégration. Le solveur calcule la position des nœuds toutes les microsecondes.
  penalty_stiffness: 2.0e+7    # [defaut=1.0e+7] La constante de raideur du contact. C'est la force mathématique qui repousse deux objets lorsqu'ils tentent de se pénétrer mutuellement.
  damping_factor: 50.0       # [defaut=] L'amortissement global du système, friction avec l'environnement : résistance de l'air, dissipation d'énergie
  contact_damping: 8000.0      # [defaut=] L'amortissement de contact : Parfaitement élastiques 1 (choc de deux boules de billard) a colle forte <1 (dissipation d'energie (chaleur) / deformation plastique)

# Base de données des propriétés physiques des matériaux
materials:
  steel:
    E: 205.0e+8             # [defaut=205 GPa = 205e+9Pa] Module de Young, force qu'il faut pour commencer à déformer le matériau (rigidité).
    nu: 0.28               # [defaut=0.28] Coefficient de Poisson, mesure le changement de largeur d'un matériau quand on tire ou pousse dessus dans le sens de la longueur.
    rho: 7850.0              # [defaut=7850] Densité (kg/m³)
    sigma_yield: 250.0e+3    # [defaut=250 MPa] Limite élastique (Pascals), point où le matériau casse ou se plie définitivement (solidité).
    limit_strain : 5.0     # [defaut=5] L'acier peut s'étirer plastiquement jusqu'à 500% avant rupture

  wood: # chêne
    E: 12.0e+8             # [defaut=12 Gpa = 12e+9 Pa]     
    nu: 0.26              # [defaut=0.26] orthotrope ramené a isotrope (une direction)
    rho: 725.0              # [defaut=725] 
    sigma_uts: 40.0e+3     # [defaut=40 MPa]
    limit_strain : 0.15   # [defaut=0.15] Si le bois s'étire de plus de 15% (0.15), ses fibres se déchirent.






